In [3]:
import numpy as np
import pandas as pd

# Load dataset
data = pd.read_csv('asiacup.csv')

# Check for NaN values in the relevant columns
print(f"NaN values in 'Run Scored': {data['Run Scored'].isna().sum()}")
print(f"NaN values in 'Wicket Lost': {data['Wicket Lost'].isna().sum()}")

# Normalize the values between 0 and 1 to represent fuzzy memberships
data['Fuzzy Run Scored'] = data['Run Scored'] / data['Run Scored'].max()
data['Fuzzy Wicket Lost'] = 1 - (data['Wicket Lost'] / data['Wicket Lost'].max())  # Invert for better performance

# Check for NaN after normalization
print(f"NaN values in normalized 'Fuzzy Run Scored': {data['Fuzzy Run Scored'].isna().sum()}")
print(f"NaN values in normalized 'Fuzzy Wicket Lost': {data['Fuzzy Wicket Lost'].isna().sum()}")

# Extract fuzzy sets
A = data['Fuzzy Run Scored'].values  # Fuzzy set A (Runs Scored)
B = data['Fuzzy Wicket Lost'].values  # Fuzzy set B (Wickets Lost)

# Fuzzy Set Operations
def fuzzy_union(A, B):
    return np.maximum(A, B)

def fuzzy_intersection(A, B):
    return np.minimum(A, B)

def fuzzy_complement(A):
    return 1 - A

def fuzzy_difference(A, B):
    return np.maximum(A - B, 0)

# Perform operations
union_result = fuzzy_union(A, B)
intersection_result = fuzzy_intersection(A, B)
complement_result_A = fuzzy_complement(A)
difference_result = fuzzy_difference(A, B)

# Print the results
print("Fuzzy Set A (Run Scored):", A[:5])
print("Fuzzy Set B (Wicket Lost):", B[:5])
print("Union (A ∪ B):", union_result[:5])
print("Intersection (A ∩ B):", intersection_result[:5])
print("Complement of A (1 - A):", complement_result_A[:5])
print("Difference (A - B):", difference_result[:5])

# Fuzzy Relations
def cartesian_product(A, B):
    return np.outer(A, B)

# Create fuzzy relation R (between A and B)
R = cartesian_product(A, B)

# Print a portion of the Cartesian product (relation)
print("\nFuzzy Relation (Cartesian Product) R:")
print(R[:5, :5])

# Max-Min Composition
def max_min_composition(R1, R2):
    if R1.shape[1] != R2.shape[0]:
        raise ValueError("The number of columns in R1 must match the number of rows in R2 for max-min composition.")
    
    result = np.zeros((R1.shape[0], R2.shape[1]))
    
    for i in range(R1.shape[0]):
        for j in range(R2.shape[1]):
            # Compute the minimum across corresponding row of R1 and column of R2
            min_values = np.minimum(R1[i, :], R2[:, j])
            # Take the maximum of those minimum values
            result[i, j] = np.max(min_values)
    
    return result

# Apply max-min composition on R with itself (for demonstration)
composition_result = max_min_composition(R, R)

# Display the corrected max-min composition result
print("\nMax-Min Composition Result (Corrected):")
print(composition_result[:5, :5])

# Check for NaN values in the Cartesian product (R)
print(f"NaN values in R: {np.isnan(R).sum()}")


NaN values in 'Run Scored': 2
NaN values in 'Wicket Lost': 2
NaN values in normalized 'Fuzzy Run Scored': 2
NaN values in normalized 'Fuzzy Wicket Lost': 2
Fuzzy Set A (Run Scored): [0.48571429 0.49350649 0.25194805 0.24935065 0.48831169]
Fuzzy Set B (Wicket Lost): [0.1 0.5 1.  0.  0.6]
Union (A ∪ B): [0.48571429 0.5        1.         0.24935065 0.6       ]
Intersection (A ∩ B): [0.1        0.49350649 0.25194805 0.         0.48831169]
Complement of A (1 - A): [0.51428571 0.50649351 0.74805195 0.75064935 0.51168831]
Difference (A - B): [0.38571429 0.         0.         0.24935065 0.        ]

Fuzzy Relation (Cartesian Product) R:
[[0.04857143 0.24285714 0.48571429 0.         0.29142857]
 [0.04935065 0.24675325 0.49350649 0.         0.2961039 ]
 [0.02519481 0.12597403 0.25194805 0.         0.15116883]
 [0.02493506 0.12467532 0.24935065 0.         0.14961039]
 [0.04883117 0.24415584 0.48831169 0.         0.29298701]]

Max-Min Composition Result (Corrected):
[[nan nan nan nan nan]
 [nan na